[package]
name = "todo-list-sycamore"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
sycamore = "0.7.0"
wasm-bindgen = "0.2"
web-sys = {version="0.3.56", features=["KeyboardEvent"]}